source 'https://rubygems.org'

gem "json", "2.6.3"

gem 'pg', force_ruby_platform: true
gem 'puma', force_ruby_platform: true
gem "sqlite3", force_ruby_platform: true
gem 'nokogiri', force_ruby_platform: true
gem 'pact_broker'
gem 'mysql2', force_ruby_platform: true
