source 'https://rubygems.org'

# gem 'yajl-ruby'
# gem 'rexml'
# gem 'bcrypt'
# gem 'charlock_holmes', force_ruby_platform: true
# gem 'curses', force_ruby_platform: true
# gem 'escape_utils'
# gem 'eventmachine', force_ruby_platform: true
# gem 'fast-stemmer'
# gem 'hitimes'
# gem 'kgio', force_ruby_platform: true
# gem 'posix-spawn', force_ruby_platform: true
# gem 'raindrops', force_ruby_platform: true
# gem 'redcarpet'
# gem 'RedCloth'
# gem 'rugged', force_ruby_platform: true
# gem 'thin'
# gem 'unf_ext'
# gem 'unicorn', force_ruby_platform: true
# ## Pact specific gems
# gem 'ffi'
gem 'pg', force_ruby_platform: true
gem 'puma', force_ruby_platform: true
gem "sqlite3", force_ruby_platform: true
gem 'nokogiri', force_ruby_platform: true
gem 'pact'
gem 'pact-support'
gem 'pact-mock_service'
gem 'pact-provider-verifier'
gem 'pact_broker-client'
gem 'pact_broker'
gem 'pact-message'
# gem 'pact-ffi'
gem 'mysql2', force_ruby_platform: true
